In [3]:
import numpy as np
from plyfile import PlyData, PlyElement

In [4]:
scene_name = 'scene0137_02'
ply_name = 'scans/' + scene_name + '/' + scene_name + '_vh_clean_2.ply' 
overs_sem = 'data_info/' + scene_name + '_overseg_sem.npy'     # every vertex overseg semantic
overs_id = 'data_info/' + scene_name + '_overseg_ids.npy'      # every vertex overseg id 

plydata = PlyData.read(ply_name)
print(plydata)
overs_n = len(plydata['vertex'])

overs_sem = np.load(overs_sem)
assert len(overs_sem)==overs_n

overs_id = np.load(overs_id)
assert len(overs_id)==overs_n

uni_overs_id = np.unique(overs_id[overs_sem!=0])
uni_n = len(uni_overs_id)
print(uni_n)

ply
format binary_little_endian 1.0
comment VCGLIB generated
element vertex 240923
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 467166
property list uchar int vertex_indices
end_header
1403


In [34]:
over_seg_color = np.random.rand(uni_n,3)*255

In [35]:
for i in range(uni_n):
    if i%50==0:
        print(i)
    for j in range(overs_n):
        if overs_sem[j] != 0 and overs_id[j]==uni_overs_id[i]:
            plydata['vertex'][j][3] = over_seg_color[i][0]
            plydata['vertex'][j][4] = over_seg_color[i][1]
            plydata['vertex'][j][5] = over_seg_color[i][2]

for j in range(overs_n):
    if overs_sem[j] == 0:
        plydata['vertex'][j][3] = 255
        plydata['vertex'][j][4] = 255
        plydata['vertex'][j][5] = 255

0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200
1250
1300
1350
1400


In [36]:
print(plydata['vertex'][1])
print(plydata['vertex'][1000])

(0.4859726, 0.3821988, 1.350402, 163, 56, 226, 255)
(0.4431134, 0.48261455, 1.0246881, 94, 108, 213, 255)


In [37]:
# import numpy as np
# print(np.load())
with open('sample_0137_02_over.ply', mode='wb') as f: 
    PlyData(plydata, text=True).write(f)

In [29]:
a = np.array([[1,2,4],[3,4,5]])
b = np.array([True,False])
a[b] = np.array([1,1,1])
print(a)

[[1 1 1]
 [3 4 5]]


In [127]:
a[:,1:3]=9

In [128]:
a

array([[1, 9, 9],
       [3, 9, 9]])

In [11]:
from scipy import stats
import numpy as np
a = np.array([[3, 0, 3, 7],
              [3, 2, 6, 2],
              [1, 7, 2, 8],
              [3, 0, 6, 1],
              [3, 2, 5, 5]])

print(stats.mode(a, 0))

ModeResult(mode=array([[3, 0, 6, 1]]), count=array([[4, 2, 2, 1]]))


In [ ]:
# convert the faces into array of N_f*3
import numpy as np
faces = []
for f in plydata['face']:
    faces.append(f[0])
faces = np.array(faces)
print(faces[1])
np.amax(faces)

count = []
for i in range(100):
    if i>0:
        print(count[-1])
    count.append(0)
    for f in faces:
        if i in f:
            count[-1]+=1
print(count[0:100])